### ISSUE TITLE
network request failed; error sending request: JsValue(Object({"message":"request to https://codeforces.com/contest/1294/problem/D failed, reason: certificate has expired","type":"system","errno":"CERT_HAS_EXPIRED","code":"CERT_HAS_EXPIRED"})); report issue?

### ISSUE THREAD

**Issue by kaizerx31** [unneon/icie#49]
I am getting this error when i try to parse any question on codeforces

**Comment by unneon** [comment]
Please update your VS Code to version 1.61.0 or later. The issue happens due to the [Let's Encrypt DST Root CA X3 expiration](https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/).
